### ISSUE TITLE
The privileged could not be raised successfully

### ISSUE THREAD

**Issue by sie249aa** [klinix5/InstallerFileTakeOver#10]
I can't change the privileged of the user. Why?
![image](https://user-images.githubusercontent.com/34031385/143820513-4fef4dce-f055-40dc-900c-d6b5eee54c9d.png)

My system info:
![image](https://user-images.githubusercontent.com/34031385/143824352-7a7b2dce-d119-4815-a348-602fbb16f8fe.png)

**Comment by Robby-Swartenbroekx** [comment]
that's not how this is supposed to work. How I understood it, it's to give a user full access rights to files it should not have.

**Comment by sie249aa** [comment]
> 
![image](https://user-images.githubusercontent.com/34031385/143827609-3f7f0bf8-a208-403e-85ea-de96d70bf4bc.png)
![image](https://user-images.githubusercontent.com/34031385/143827648-a7361f11-90b3-4096-accd-8b4b9d9ba4bb.png)

it's not work too.

**Comment by Robby-Swartenbroekx** [comment]
don't going to defend it here, because it also don't get it to work as intended.

**Comment by jc19930401** [comment]
InstallerFileTakeOver.exe doesn't work.
<img width="1314" alt="截圖 2021-11-29 下午3 58 39" src="https://user-images.githubusercontent.com/37798944/143835233-7980c26d-3ae6-4a45-bfbb-e77b97eab128.png">

**Comment by klinix5** [comment]
If you don't understand how windows work, please don't open an issue.
