### ISSUE TITLE
How to get it working on Windows Server 2019 and 2016

### ISSUE THREAD

**Issue by deathalliance** [klinix5/InstallerFileTakeOver#9]
Hi, I got it successfully working on a Win 10, but Windows Server 2019 would not work **even with Microsoft Edge Elevation Service installed**.
I made some changes to the code to test other services for the same purpose, but none of them worked.

Then I tried installing the `test pkg.msi` file manually, and noticed the behavior differed in Win 2019. On a Win 10, the installer would finish but on Win 2019 it stopped on the Rollback stage. It was also looking for a c:\test\notepad.exe file in the Win 2019 version.

Side note: this code empties any document it takes over, so a takeover of win.ini effectively zeroed out that file. Should be good to know for anyone working in a lab environment.

**Comment by klinix5** [comment]
https://github.com/sailay1996/awesome_windows_logical_bugs/blob/master/FileWrite2system.txt
